name: korkimatematyczne
description: A library used to scrape korkimatematyczne.blogspot.com website
version: 1.0.0-rc
repository: https://github.com/B-P-Coders/korkimatematyczne

environment:
  sdk: ^3.1.3

dependencies:
  embed_annotation: ^1.2.0
  web_scraper: ^0.1.4

dev_dependencies:
  build_runner: ^2.4.6
  embed: ^1.2.0
  lints: ^2.0.0
  test: ^1.21.0
