name: korkimatematyczne
description: A library used to scrape korkimatematyczne.blogspot.com website
version: 0.1.0
repository: https://github.com/B-P-Coders/korkimatematyczne

environment:
  sdk: ^3.1.3

dependencies:
  web_scraper: ^0.1.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
